name: deploy

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-blog]

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  trigger:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Triggered by content repository!, version ${{ github.event.client_payload.version }}"
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install, build, and upload your site
        uses: withastro/action@v6

  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release and push git tag
        run: "git tag $(jq -r '.version' package.json) && git push --tags"
      - name: Create a GitHub release
        run: "gh release create $(jq -r '.version' package.json) --generate-notes"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
